// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plupxsvignvnrdezmdna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdXB4c3ZpZ252bnJkZXptZG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjI4NjEsImV4cCI6MjA2NTczODg2MX0.Ou0KaJCnvHXBGXEhPkxwKe-znza_joB7GVj1NhwZeSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});